---
- name: "install | add maas ppa repository"
  apt_repository:
    repo: "{{ maas.repository }}"
    state: "present"
    update_cache: true

- name: "install | ensure requirements are installed"
  package:
    name: "{{ maas_regiond.requirements }}"
    state: "present"
    update_cache: true
    cache_valid_time: 3600

- name: "install | install all maas components (single-node)"
  package:
    name: "maas"
    state: "present"
    update_cache: true
    cache_valid_time: 3600
  when: maas.single_node
  notify: "init maas controller"

- name: "install | install maas-region-controller"
  package:
    name: "{{ maas_regiond.package }}"
    state: "present"
    update_cache: true
    cache_valid_time: 3600
  when: not maas.single_node
  notify: "init maas controller"

- name: "install | update postgres password"
  postgresql_user:
    db: "{{ maas_database.name }}"
    name: "{{ maas_database.user }}"
    password: "{{ maas_database.password | mandatory() }}"
    encrypted: yes
  become: true
  become_user: postgres

- name: "install | install kvm support"
  package:
    name: "{{ _kvm }}"
    state: "present"
  loop:
    - "libvirt-bin"
    - "libvirt-clients"
    - "libvirt-daemon-system"
    - "qemu-kvm"
  loop_control:
    loop_var: _kvm
  when: maas_regiond.kvm
