---
- name: "restart maas-regiond"
  service:
    name: "maas-regiond"
    state: "restarted"
  listen: "restart all maas-regiond services"

- name: "restart maas-dhcpd"
  service:
    name: "maas-dhcpd"
    state: "restarted"
  listen: "restart all maas-regiond services"

- name: "restart maas-http"
  service:
    name: "maas-http"
    state: "restarted"
  listen: "restart all maas-regiond services"

- name: "restart maas-proxy"
  service:
    name: "maas-proxy"
    state: "restarted"
  listen: "restart all maas-regiond services"

- name: "restart maas-syslog"
  service:
    name: "maas-syslog"
    state: "restarted"
  listen: "restart all maas-regiond services"

- name: "mark admin users as created"
  file:
    path: "/etc/maas/.admin_users_created"
    state: "touch"

- name: "init maas controller"
  shell: "maas init --skip-admin"
  args:
    executable: "/bin/bash"
    creates: "/var/lib/maas/secret"
